# Generated by Django 6.0.4 on 2026-05-10 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measure', models.CharField(default='TRAINING')),
                ('date', models.DateTimeField()),
                ('level', models.CharField(choices=[('Fi', 'First'), ('FN', 'First-Next'), ('Ne', 'Next'), ('NL', 'Next-Light'), ('Li', 'Light'), ('LM', 'Light-Medium'), ('Me', 'Medium'), ('MA', 'Medium-Advanced'), ('Ad', 'Advanced'), ('AH', 'Advanced-Hard'), ('Ha', 'Hard'), ('HM', 'Hard-Master'), ('Ma', 'Master')], db_index=True, max_length=2)),
                ('place', models.CharField()),
                ('max_member', models.IntegerField(blank=True, null=True)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='events/default.png', null=True, upload_to='events')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
            ],
        ),
    ]
