# Generated by Django 6.0.4 on 2026-04-26 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measure', models.CharField(default='TRAINING')),
                ('date', models.DateTimeField()),
                ('level', models.CharField(choices=[('F', 'First'), ('N', 'Next'), ('L', 'Light'), ('M', 'Medium'), ('A', 'Advanced'), ('H', 'Hard'), ('P', 'Professional')], db_index=True, max_length=1)),
                ('place', models.CharField()),
                ('max_member', models.IntegerField(blank=True, null=True)),
                ('message_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
            ],
        ),
    ]
