# Generated by Django 6.0.4 on 2026-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('Fi', 'First'), ('Ne', 'Next'), ('Li', 'Light'), ('Me', 'Medium'), ('Ad', 'Advanced'), ('Ha', 'Hard'), ('Ma', 'Master')], db_index=True, max_length=2),
        ),
    ]
