# Generated by Django 6.0.4 on 2026-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='events/default.png', null=True, upload_to='events'),
        ),
    ]
