# Generated by Django 6.0.4 on 2026-04-26 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=uuid.uuid4),
        ),
    ]
